"use client";

import { useEffect, useRef, useState } from "react";
import { createChart, createSeriesMarkers, CandlestickSeries, LineSeries, ColorType, type UTCTimestamp } from "lightweight-charts";
import { evaluatePrimeAt, type PrimeCandle, type PrimeSignal } from "@/lib/prime";

const SYMBOLS = ["RELIANCE", "HDFCBANK", "SBIN", "INFY"];
const TIMEFRAMES = [{ label: "1 MIN", value: "1" }, { label: "3 MIN", value: "3" }, { label: "5 MIN", value: "5" }, { label: "15 MIN", value: "15" }];
type Candle = PrimeCandle;
type LiveMessage = { type: string; symbol?: string; ltp?: number; candle?: { time: number; open: number; high: number; low: number; close: number; volume: number } };

function emaData(candles: Candle[], period = 20) { if (candles.length < period) return []; let e = candles.slice(0, period).reduce((s, c) => s + c.close, 0) / period; const k = 2 / (period + 1); const out: any[] = [{ time: candles[period - 1].time as UTCTimestamp, value: e }]; for (let i = period; i < candles.length; i++) { e = candles[i].close * k + e * (1 - k); out.push({ time: candles[i].time as UTCTimestamp, value: e }); } return out; }
function dayKey(t: number) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(t * 1000)); }
function previousLevels(candles: Candle[]) { const days = new Map<string, { high: number; low: number }>(); for (const c of candles) { const d = dayKey(c.time); const x = days.get(d); if (!x) days.set(d, { high: c.high, low: c.low }); else { x.high = Math.max(x.high, c.high); x.low = Math.min(x.low, c.low); } } const dates = [...days.keys()].sort(); const out = new Map<string, { high: number; low: number; mid: number }>(); for (let i = 1; i < dates.length; i++) { const x = days.get(dates[i - 1]); if (x) out.set(dates[i], { high: x.high, low: x.low, mid: (x.high + x.low) / 2 }); } return out; }
function aggregate(minutes: Candle[], n: number): Candle | null { if (!minutes.length) return null; const s = [...minutes].sort((a, b) => a.time - b.time); const bucket = n * 60; const t = Math.floor(s[0].time / bucket) * bucket; return { time: t, open: s[0].open, high: Math.max(...s.map(x => x.high)), low: Math.min(...s.map(x => x.low)), close: s[s.length - 1].close, volume: s.reduce((a, x) => a + x.volume, 0) }; }
function signalMarkers(candles: Candle[]) { const completed = candles.slice(0, Math.max(0, candles.length - 1)); const markers: any[] = []; const seen = new Set<string>(); for (let i = 0; i < completed.length; i++) { const s = evaluatePrimeAt(completed, i, "QUALITY PRIME"); if (!s.confirmation && !s.fakeBreakout) continue; const key = `${completed[i].time}:${s.direction}`; if (seen.has(key)) continue; seen.add(key); const down = s.direction === "SELL" || s.direction === "FAKE BEAR"; markers.push({ time: completed[i].time as UTCTimestamp, position: down ? "aboveBar" : "belowBar", color: down ? "#ef4444" : "#22c55e", shape: down ? "arrowDown" : "arrowUp", text: s.direction === "BUY" ? "BUY" : s.direction === "SELL" ? "SELL" : s.direction }); } return markers; }

export default function Home() {
  const chartRef = useRef<HTMLDivElement>(null); const candleRef = useRef<any>(null); const emaRef = useRef<any>(null); const yhRef = useRef<any>(null); const ylRef = useRef<any>(null); const midRef = useRef<any>(null); const markerRef = useRef<any>(null); const candlesRef = useRef<Candle[]>([]); const minuteMapRef = useRef(new Map<number, Candle>());
  const [symbol, setSymbol] = useState("RELIANCE"); const [timeframe, setTimeframe] = useState("5"); const [connected, setConnected] = useState(false); const [upstox, setUpstox] = useState(false); const [ltp, setLtp] = useState<number | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [signals, setSignals] = useState<Array<{ time: number; signal: PrimeSignal; candle: Candle }>>([]); const [currentSignal, setCurrentSignal] = useState<PrimeSignal | null>(null);

  useEffect(() => { fetch("/api/upstox/status", { cache: "no-store" }).then(r => r.json()).then(x => setUpstox(Boolean(x.connected))).catch(() => setUpstox(false)); }, []);

  useEffect(() => {
    if (!chartRef.current) return; let dead = false; const chart = createChart(chartRef.current, { layout: { background: { type: ColorType.Solid, color: "#070b10" }, textColor: "#d1d5db" }, grid: { vertLines: { color: "#17202b" }, horzLines: { color: "#17202b" } }, width: chartRef.current.clientWidth, height: 650, timeScale: { timeVisible: true, secondsVisible: false }, rightPriceScale: { borderColor: "#334155" } });
    const candle = chart.addSeries(CandlestickSeries, { upColor: "#22c55e", downColor: "#ef4444", borderVisible: false, wickUpColor: "#22c55e", wickDownColor: "#ef4444" }); const ema = chart.addSeries(LineSeries, { color: "#facc15", lineWidth: 2, priceLineVisible: false }); const yh = chart.addSeries(LineSeries, { color: "#38bdf8", lineWidth: 1, lineStyle: 2, priceLineVisible: false }); const yl = chart.addSeries(LineSeries, { color: "#f87171", lineWidth: 1, lineStyle: 2, priceLineVisible: false }); const mid = chart.addSeries(LineSeries, { color: "#a78bfa", lineWidth: 1, lineStyle: 2, priceLineVisible: false });
    candleRef.current = candle; emaRef.current = ema; yhRef.current = yh; ylRef.current = yl; midRef.current = mid; markerRef.current = createSeriesMarkers(candle, []);
    const render = (candles: Candle[]) => { candlesRef.current = candles; candle.setData(candles as any); ema.setData(emaData(candles) as any); const lv = previousLevels(candles); const yhD: any[] = [], ylD: any[] = [], midD: any[] = []; for (const c of candles) { const x = lv.get(dayKey(c.time)); if (x) { yhD.push({ time: c.time as UTCTimestamp, value: x.high }); ylD.push({ time: c.time as UTCTimestamp, value: x.low }); midD.push({ time: c.time as UTCTimestamp, value: x.mid }); } } yh.setData(yhD); yl.setData(ylD); mid.setData(midD); markerRef.current?.setMarkers(signalMarkers(candles)); const completed = candles.length ? candles.length - 1 : -1; if (completed >= 0) setCurrentSignal(evaluatePrimeAt(candles, completed, "QUALITY PRIME")); };
    (async () => { try { setLoading(true); setError(""); const r = await fetch(`/api/upstox/history?symbol=${symbol}&interval=${timeframe}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Failed to load Upstox candles"); const candles = (d.candles || []).map((x: any) => ({ time: Math.floor(new Date(x[0]).getTime() / 1000), open: +x[1], high: +x[2], low: +x[3], close: +x[4], volume: +x[5] })).sort((a: Candle, b: Candle) => a.time - b.time); if (!dead) { render(candles); chart.timeScale().fitContent(); } } catch (e) { if (!dead) setError(e instanceof Error ? e.message : "Chart data error"); } finally { if (!dead) setLoading(false); } })(); const ro = new ResizeObserver(() => chartRef.current && chart.applyOptions({ width: chartRef.current.clientWidth })); ro.observe(chartRef.current); return () => { dead = true; ro.disconnect(); chart.remove(); candleRef.current = null; emaRef.current = null; markerRef.current = null; };
  }, [symbol, timeframe]);

  useEffect(() => { let dead = false; minuteMapRef.current.clear(); const protocol = window.location.protocol === "https:" ? "wss:" : "ws:"; const ws = new WebSocket(`${protocol}//${window.location.host}/api/ws`); const n = Number(timeframe);
    ws.onopen = () => { if (!dead) setConnected(true); ws.send(JSON.stringify({ type: "subscribe", symbol })); }; ws.onclose = () => !dead && setConnected(false); ws.onerror = () => !dead && setConnected(false);
    ws.onmessage = e => { try { const p = JSON.parse(e.data) as LiveMessage; if (p.type === "connected") { setConnected(true); return; } if (p.type !== "live_1m" || p.symbol !== symbol || !p.candle) return; setLtp(Number(p.ltp)); const x = p.candle; const t = Math.floor(Number(x.time) / 60) * 60; minuteMapRef.current.set(t, { time: t, open: +x.open, high: +x.high, low: +x.low, close: +x.close, volume: +x.volume }); const bucket = Math.floor(t / (n * 60)) * n * 60; const mins = [...minuteMapRef.current.values()].filter(c => c.time >= bucket && c.time < bucket + n * 60); const live = aggregate(mins, n); if (!live || !candleRef.current) return; const merged = [...candlesRef.current.filter(c => c.time !== live.time), live].sort((a, b) => a.time - b.time); candlesRef.current = merged; candleRef.current.update(live as any); emaRef.current?.setData(emaData(merged) as any); const lv = previousLevels(merged).get(dayKey(live.time)); if (lv) { yhRef.current?.update({ time: live.time as UTCTimestamp, value: lv.high }); ylRef.current?.update({ time: live.time as UTCTimestamp, value: lv.low }); midRef.current?.update({ time: live.time as UTCTimestamp, value: lv.mid }); } markerRef.current?.setMarkers(signalMarkers(merged)); const completed = merged.length - 1; if (completed >= 0) { const s = evaluatePrimeAt(merged, completed, "QUALITY PRIME"); setCurrentSignal(s); if (s.confirmation || s.fakeBreakout) setSignals(prev => { const key = `${merged[completed].time}:${s.direction}`; return prev.some(x => `${x.time}:${x.signal.direction}` === key) ? prev : [{ time: merged[completed].time, signal: s, candle: merged[completed] }, ...prev].slice(0, 20); }); } } catch {} };
    return () => { dead = true; ws.close(); setConnected(false); };
  }, [symbol, timeframe]);

  const label = TIMEFRAMES.find(x => x.value === timeframe)?.label || `${timeframe} MIN`;
  return <main className="min-h-screen bg-black text-white"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-gray-800 px-5 py-4"><div><h1 className="text-xl font-bold">PRIME TECHNICAL</h1><p className="text-xs text-gray-500">Upstox V3 • PRIME Quality Engine • Vercel Live</p></div><div className="flex flex-wrap items-center gap-2"><select value={symbol} onChange={e => setSymbol(e.target.value)} className="rounded bg-gray-900 px-3 py-2 text-sm">{SYMBOLS.map(x => <option key={x}>{x}</option>)}</select><select value={timeframe} onChange={e => setTimeframe(e.target.value)} className="rounded bg-gray-900 px-3 py-2 text-sm">{TIMEFRAMES.map(x => <option key={x.value} value={x.value}>{x.label}</option>)}</select>{upstox ? <span className="rounded bg-green-950 px-3 py-2 text-xs text-green-400">● UPSTOX CONNECTED</span> : <a href="/api/upstox/login" className="rounded bg-purple-700 px-3 py-2 text-xs font-semibold">CONNECT UPSTOX</a>}<span className={connected ? "rounded bg-green-950 px-3 py-2 text-xs text-green-400" : "rounded bg-gray-900 px-3 py-2 text-xs text-gray-500"}>● {connected ? "LIVE FEED" : "OFFLINE"}</span>{ltp !== null && <span className="font-semibold">₹{ltp.toFixed(2)}</span>}</div></header>
    <section className="p-4"><div className="mb-3 flex flex-wrap gap-4 text-xs text-gray-400"><span>{symbol}</span><span>{label}</span><span className="text-yellow-400">EMA20</span><span className="text-sky-400">YH / PDH</span><span className="text-red-400">YL / PDL</span><span className="text-purple-400">MID</span>{loading && <span>Loading…</span>}</div>{error && <div className="mb-3 rounded border border-red-900 bg-red-950/40 p-3 text-sm text-red-300">DATA ERROR: {error}</div>}<div ref={chartRef} className="w-full overflow-hidden rounded-lg border border-gray-800" />
      <div className="mt-4 grid gap-3 md:grid-cols-4"><div className="rounded border border-gray-800 bg-gray-950 p-3"><div className="text-[10px] text-gray-500">STATE</div><div className="mt-1 font-semibold">{currentSignal?.state || "—"}</div></div><div className="rounded border border-gray-800 bg-gray-950 p-3"><div className="text-[10px] text-gray-500">DIRECTION</div><div className="mt-1 font-semibold">{currentSignal?.direction || "—"}</div></div><div className="rounded border border-gray-800 bg-gray-950 p-3"><div className="text-[10px] text-gray-500">PRIME SCORE</div><div className="mt-1 font-semibold">{currentSignal?.score?.toFixed(1) || "—"} {currentSignal?.grade && currentSignal.grade !== "—" ? `• ${currentSignal.grade}` : ""}</div></div><div className="rounded border border-gray-800 bg-gray-950 p-3"><div className="text-[10px] text-gray-500">VOLUME</div><div className="mt-1 font-semibold">{currentSignal ? `${currentSignal.volumeMultiple.toFixed(2)}X` : "—"}</div></div></div>
      <div className="mt-4 rounded border border-gray-800 bg-gray-950 p-3"><div className="mb-2 text-xs font-semibold text-gray-300">SIGNAL DETAILS</div><div className="grid gap-2 text-xs text-gray-400 md:grid-cols-4"><span>Trigger: {currentSignal?.triggerLevel?.toFixed(2) || "—"}</span><span>EMA20: {currentSignal?.ema20?.toFixed(2) || "—"}</span><span>SL: {currentSignal?.structuralSL?.toFixed(2) || "—"}</span><span>Risk Qty: {currentSignal?.riskQuantity ?? "—"}</span></div><p className="mt-2 text-xs text-gray-500">{currentSignal?.reason || "Waiting for data"}</p></div>
      <div className="mt-4 rounded border border-gray-800 bg-gray-950 p-3"><div className="mb-2 text-xs font-semibold text-gray-300">CONFIRMED SIGNAL HISTORY • SIGNAL-TIME VALUES</div>{signals.length === 0 ? <div className="text-xs text-gray-600">No completed PRIME signal yet.</div> : <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-gray-600"><tr><th className="p-2">TIME</th><th>DIR</th><th>STATE</th><th>PRICE</th><th>VOLUME</th><th>SCORE</th><th>SL</th><th>REASON</th></tr></thead><tbody>{signals.map(x => <tr key={`${x.time}-${x.signal.direction}`} className="border-t border-gray-900"><td className="p-2">{new Date(x.time * 1000).toLocaleTimeString("en-IN", { timeZone: "Asia/Kolkata", hour: "2-digit", minute: "2-digit" })}</td><td className={x.signal.direction === "BUY" ? "text-green-400" : "text-red-400"}>{x.signal.direction}</td><td>{x.signal.state}</td><td>{x.candle.close.toFixed(2)}</td><td>{x.signal.volumeMultiple.toFixed(2)}X</td><td>{x.signal.score?.toFixed(1) || "—"} {x.signal.grade}</td><td>{x.signal.structuralSL?.toFixed(2) || "—"}</td><td className="max-w-md text-gray-500">{x.signal.reason}</td></tr>)}</tbody></table></div>}</div>
    </section></main>;
}
